/*
 * Activated Assets' Search API
 * API definition for Activated Assets' Search Capabilities
 *
 * OpenAPI spec version: 0.2.0-experimental
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CompositeQuery;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Logical and operator. The results must match all the sub-queries in this clause. e.g. &#x60;&#x60;&#x60; \&quot;and\&quot;: [   {     \&quot;match\&quot;: {       \&quot;text\&quot;: \&quot;blue\&quot;     }   },   {     \&quot;match\&quot;: {       \&quot;text\&quot;: \&quot;white\&quot;     }   } ] &#x60;&#x60;&#x60; 
 */
@Schema(description = "Logical and operator. The results must match all the sub-queries in this clause. e.g. ``` \"and\": [   {     \"match\": {       \"text\": \"blue\"     }   },   {     \"match\": {       \"text\": \"white\"     }   } ] ``` ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-30T19:07:33.419517+05:30[Asia/Kolkata]")
public class AndQuery implements CompositeQuery {
  @SerializedName("and")
  private List<CompositeQuery> and = new ArrayList<CompositeQuery>();

  public AndQuery and(List<CompositeQuery> and) {
    this.and = and;
    return this;
  }

  public AndQuery addAndItem(CompositeQuery andItem) {
    this.and.add(andItem);
    return this;
  }

   /**
   * Get and
   * @return and
  **/
  @Schema(required = true, description = "")
  public List<CompositeQuery> getAnd() {
    return and;
  }

  public void setAnd(List<CompositeQuery> and) {
    this.and = and;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AndQuery andQuery = (AndQuery) o;
    return Objects.equals(this.and, andQuery.and);
  }

  @Override
  public int hashCode() {
    return Objects.hash(and);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AndQuery {\n");
    
    sb.append("    and: ").append(toIndentedString(and)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
