/*
 * Activated Assets' Search API
 * API definition for Activated Assets' Search Capabilities
 *
 * OpenAPI spec version: 0.2.0-experimental
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.MatchQueryMatch;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Search for Full text (supports contains/startswith/endswith/fuzzy) e.g. &#x60;&#x60;&#x60; \&quot;match\&quot;: {   \&quot;text\&quot;: \&quot;crocs\&quot;,   \&quot;operator\&quot;: \&quot;contains\&quot;,   \&quot;fields\&quot;: [     \&quot;metadata.repository.repo:name\&quot;,     \&quot;metadata.application.xcm:machineKeywords.value\&quot;   ] } &#x60;&#x60;&#x60; 
 */
@Schema(description = "Search for Full text (supports contains/startswith/endswith/fuzzy) e.g. ``` \"match\": {   \"text\": \"crocs\",   \"operator\": \"contains\",   \"fields\": [     \"metadata.repository.repo:name\",     \"metadata.application.xcm:machineKeywords.value\"   ] } ``` ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-30T19:07:33.419517+05:30[Asia/Kolkata]")
public class MatchQuery implements CompositeQuery {
  @SerializedName("match")
  private MatchQueryMatch match = null;

  public MatchQuery match(MatchQueryMatch match) {
    this.match = match;
    return this;
  }

   /**
   * Get match
   * @return match
  **/
  @Schema(required = true, description = "")
  public MatchQueryMatch getMatch() {
    return match;
  }

  public void setMatch(MatchQueryMatch match) {
    this.match = match;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchQuery matchQuery = (MatchQuery) o;
    return Objects.equals(this.match, matchQuery.match);
  }

  @Override
  public int hashCode() {
    return Objects.hash(match);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchQuery {\n");
    
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
