/*
 * Activated Assets' Search API
 * API definition for Activated Assets' Search Capabilities
 *
 * OpenAPI spec version: 0.2.0-experimental
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CompositeQuery;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Logical not operator. All matches are excluded from the results e.g. &#x60;&#x60;&#x60; \&quot;not\&quot;: [   \&quot;term\&quot;: {     \&quot;metadata.repository.dc:format\&quot;: [       \&quot;video/mp4\&quot;     ]   } ] &#x60;&#x60;&#x60; 
 */
@Schema(description = "Logical not operator. All matches are excluded from the results e.g. ``` \"not\": [   \"term\": {     \"metadata.repository.dc:format\": [       \"video/mp4\"     ]   } ] ``` ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-30T19:07:33.419517+05:30[Asia/Kolkata]")
public class NotQuery implements CompositeQuery {
  @SerializedName("not")
  private List<CompositeQuery> not = new ArrayList<CompositeQuery>();

  public NotQuery not(List<CompositeQuery> not) {
    this.not = not;
    return this;
  }

  public NotQuery addNotItem(CompositeQuery notItem) {
    this.not.add(notItem);
    return this;
  }

   /**
   * Get not
   * @return not
  **/
  @Schema(required = true, description = "")
  public List<CompositeQuery> getNot() {
    return not;
  }

  public void setNot(List<CompositeQuery> not) {
    this.not = not;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotQuery notQuery = (NotQuery) o;
    return Objects.equals(this.not, notQuery.not);
  }

  @Override
  public int hashCode() {
    return Objects.hash(not);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotQuery {\n");
    
    sb.append("    not: ").append(toIndentedString(not)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
