/*
 * Activated Assets' Search API
 * API definition for Activated Assets' Search Capabilities
 *
 * OpenAPI spec version: 0.2.0-experimental
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RangeQueryRange
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-30T19:07:33.419517+05:30[Asia/Kolkata]")
public class RangeQueryRange {
  @SerializedName("gt")
  private Object gt = null;

  @SerializedName("gte")
  private Object gte = null;

  @SerializedName("lt")
  private Object lt = null;

  @SerializedName("lte")
  private Object lte = null;

  public RangeQueryRange gt(Object gt) {
    this.gt = gt;
    return this;
  }

   /**
   * Greater-than
   * @return gt
  **/
  @Schema(description = "Greater-than")
  public Object getGt() {
    return gt;
  }

  public void setGt(Object gt) {
    this.gt = gt;
  }

  public RangeQueryRange gte(Object gte) {
    this.gte = gte;
    return this;
  }

   /**
   * Greater-than or equal-to
   * @return gte
  **/
  @Schema(description = "Greater-than or equal-to")
  public Object getGte() {
    return gte;
  }

  public void setGte(Object gte) {
    this.gte = gte;
  }

  public RangeQueryRange lt(Object lt) {
    this.lt = lt;
    return this;
  }

   /**
   * Less-than
   * @return lt
  **/
  @Schema(description = "Less-than")
  public Object getLt() {
    return lt;
  }

  public void setLt(Object lt) {
    this.lt = lt;
  }

  public RangeQueryRange lte(Object lte) {
    this.lte = lte;
    return this;
  }

   /**
   * Less-than or equal-to
   * @return lte
  **/
  @Schema(description = "Less-than or equal-to")
  public Object getLte() {
    return lte;
  }

  public void setLte(Object lte) {
    this.lte = lte;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RangeQueryRange rangeQueryRange = (RangeQueryRange) o;
    return Objects.equals(this.gt, rangeQueryRange.gt) &&
        Objects.equals(this.gte, rangeQueryRange.gte) &&
        Objects.equals(this.lt, rangeQueryRange.lt) &&
        Objects.equals(this.lte, rangeQueryRange.lte);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gt, gte, lt, lte);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RangeQueryRange {\n");
    
    sb.append("    gt: ").append(toIndentedString(gt)).append("\n");
    sb.append("    gte: ").append(toIndentedString(gte)).append("\n");
    sb.append("    lt: ").append(toIndentedString(lt)).append("\n");
    sb.append("    lte: ").append(toIndentedString(lte)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
