/*
 * Activated Assets' Search API
 * API definition for Activated Assets' Search Capabilities
 *
 * OpenAPI spec version: 0.2.0-experimental
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SearchResponseSearchMetadata
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-30T19:07:33.419517+05:30[Asia/Kolkata]")
public class SearchResponseSearchMetadata {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("took")
  private Long took = null;

  public SearchResponseSearchMetadata count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * minimum: 0
   * @return count
  **/
  @Schema(required = true, description = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public SearchResponseSearchMetadata took(Long took) {
    this.took = took;
    return this;
  }

   /**
   * Get took
   * @return took
  **/
  @Schema(required = true, description = "")
  public Long getTook() {
    return took;
  }

  public void setTook(Long took) {
    this.took = took;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponseSearchMetadata searchResponseSearchMetadata = (SearchResponseSearchMetadata) o;
    return Objects.equals(this.count, searchResponseSearchMetadata.count) &&
        Objects.equals(this.took, searchResponseSearchMetadata.took);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, took);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponseSearchMetadata {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    took: ").append(toIndentedString(took)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
