/*
 * Activated Assets' Search API
 * API definition for Activated Assets' Search Capabilities
 *
 * OpenAPI spec version: 0.2.0-experimental
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.SearchResponseHits;
import io.swagger.client.model.SearchResponseSearchMetadata;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SearchResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-30T19:07:33.419517+05:30[Asia/Kolkata]")
public class SearchResponse {
  @SerializedName("hits")
  private SearchResponseHits hits = null;

  @SerializedName("search_metadata")
  private SearchResponseSearchMetadata searchMetadata = null;

  public SearchResponse hits(SearchResponseHits hits) {
    this.hits = hits;
    return this;
  }

   /**
   * Get hits
   * @return hits
  **/
  @Schema(required = true, description = "")
  public SearchResponseHits getHits() {
    return hits;
  }

  public void setHits(SearchResponseHits hits) {
    this.hits = hits;
  }

  public SearchResponse searchMetadata(SearchResponseSearchMetadata searchMetadata) {
    this.searchMetadata = searchMetadata;
    return this;
  }

   /**
   * Get searchMetadata
   * @return searchMetadata
  **/
  @Schema(required = true, description = "")
  public SearchResponseSearchMetadata getSearchMetadata() {
    return searchMetadata;
  }

  public void setSearchMetadata(SearchResponseSearchMetadata searchMetadata) {
    this.searchMetadata = searchMetadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponse searchResponse = (SearchResponse) o;
    return Objects.equals(this.hits, searchResponse.hits) &&
        Objects.equals(this.searchMetadata, searchResponse.searchMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hits, searchMetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponse {\n");
    
    sb.append("    hits: ").append(toIndentedString(hits)).append("\n");
    sb.append("    searchMetadata: ").append(toIndentedString(searchMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
