/*
 * Activated Assets' Search API
 * API definition for Activated Assets' Search Capabilities
 *
 * OpenAPI spec version: 0.2.0-experimental
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Sortable
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-30T19:07:33.419517+05:30[Asia/Kolkata]")
public class Sortable {
  @SerializedName("by")
  private String by = null;

  /**
   * sorting order - ascending or descending
   */
  @JsonAdapter(OrderEnum.Adapter.class)
  public enum OrderEnum {
    ASC("asc"),
    DESC("desc");

    private String value;

    OrderEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static OrderEnum fromValue(String input) {
      for (OrderEnum b : OrderEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<OrderEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OrderEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public OrderEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return OrderEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("order")
  private OrderEnum order = OrderEnum.ASC;

  public Sortable by(String by) {
    this.by = by;
    return this;
  }

   /**
   * field name on which to order search results, ignored if not present in the data (wrongly specified)
   * @return by
  **/
  @Schema(example = "size", required = true, description = "field name on which to order search results, ignored if not present in the data (wrongly specified)")
  public String getBy() {
    return by;
  }

  public void setBy(String by) {
    this.by = by;
  }

  public Sortable order(OrderEnum order) {
    this.order = order;
    return this;
  }

   /**
   * sorting order - ascending or descending
   * @return order
  **/
  @Schema(required = true, description = "sorting order - ascending or descending")
  public OrderEnum getOrder() {
    return order;
  }

  public void setOrder(OrderEnum order) {
    this.order = order;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sortable sortable = (Sortable) o;
    return Objects.equals(this.by, sortable.by) &&
        Objects.equals(this.order, sortable.order);
  }

  @Override
  public int hashCode() {
    return Objects.hash(by, order);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sortable {\n");
    
    sb.append("    by: ").append(toIndentedString(by)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
