/*
 * Activated Assets' Search API
 * API definition for Activated Assets' Search Capabilities
 *
 * OpenAPI spec version: 0.2.0-experimental
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Problem;
import io.swagger.client.model.SearchRequest;
import io.swagger.client.model.SearchResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ActivatedAssetsSearchApi
 */
@Ignore
public class ActivatedAssetsSearchApiTest {

    private final ActivatedAssetsSearchApi api = new ActivatedAssetsSearchApi();

    /**
     * Search for activated assets based on specified criteria
     *
     * Search Activated Assets
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void searchTest() throws Exception {
        SearchRequest body = null;
        SearchResponse response = api.search(body);

        // TODO: test validations
    }
}
